# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addremove_records.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 525)
        self.add_btn = QtWidgets.QPushButton(Dialog)
        self.add_btn.setGeometry(QtCore.QRect(50, 300, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.remove_btn = QtWidgets.QPushButton(Dialog)
        self.remove_btn.setGeometry(QtCore.QRect(50, 460, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.remove_btn.setFont(font)
        self.remove_btn.setObjectName("remove_btn")
        self.artist = QtWidgets.QLabel(Dialog)
        self.artist.setGeometry(QtCore.QRect(50, 150, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.artist.setFont(font)
        self.artist.setObjectName("artist")
        self.add_record = QtWidgets.QLabel(Dialog)
        self.add_record.setGeometry(QtCore.QRect(50, 110, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_record.setFont(font)
        self.add_record.setObjectName("add_record")
        self.duration = QtWidgets.QLabel(Dialog)
        self.duration.setGeometry(QtCore.QRect(50, 230, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.duration.setFont(font)
        self.duration.setObjectName("duration")
        self.tracks = QtWidgets.QLabel(Dialog)
        self.tracks.setGeometry(QtCore.QRect(200, 230, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tracks.setFont(font)
        self.tracks.setObjectName("tracks")
        self.record_label = QtWidgets.QLabel(Dialog)
        self.record_label.setGeometry(QtCore.QRect(50, 190, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.record_label.setFont(font)
        self.record_label.setObjectName("record_label")
        self.grade = QtWidgets.QLabel(Dialog)
        self.grade.setGeometry(QtCore.QRect(380, 230, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.grade.setFont(font)
        self.grade.setObjectName("grade")
        self.goat_box = QtWidgets.QCheckBox(Dialog)
        self.goat_box.setGeometry(QtCore.QRect(50, 270, 451, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.goat_box.setFont(font)
        self.goat_box.setObjectName("goat_box")
        self.add_title = QtWidgets.QLabel(Dialog)
        self.add_title.setGeometry(QtCore.QRect(40, 10, 461, 81))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.add_title.setFont(font)
        self.add_title.setObjectName("add_title")
        self.track_input = QtWidgets.QLineEdit(Dialog)
        self.track_input.setGeometry(QtCore.QRect(310, 230, 61, 21))
        self.track_input.setObjectName("track_input")
        self.score_input = QtWidgets.QLineEdit(Dialog)
        self.score_input.setGeometry(QtCore.QRect(430, 230, 61, 21))
        self.score_input.setObjectName("score_input")
        self.record_input = QtWidgets.QLineEdit(Dialog)
        self.record_input.setGeometry(QtCore.QRect(110, 110, 381, 21))
        self.record_input.setObjectName("record_input")
        self.artist_input = QtWidgets.QLineEdit(Dialog)
        self.artist_input.setGeometry(QtCore.QRect(120, 150, 371, 21))
        self.artist_input.setObjectName("artist_input")
        self.record_label_input = QtWidgets.QLineEdit(Dialog)
        self.record_label_input.setGeometry(QtCore.QRect(150, 190, 341, 21))
        self.record_label_input.setObjectName("record_label_input")
        self.remove_record = QtWidgets.QLabel(Dialog)
        self.remove_record.setGeometry(QtCore.QRect(50, 420, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.remove_record.setFont(font)
        self.remove_record.setObjectName("remove_record")
        self.remove_input = QtWidgets.QLineEdit(Dialog)
        self.remove_input.setGeometry(QtCore.QRect(110, 420, 381, 21))
        self.remove_input.setObjectName("remove_input")
        self.remove_title = QtWidgets.QLabel(Dialog)
        self.remove_title.setGeometry(QtCore.QRect(100, 370, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.remove_title.setFont(font)
        self.remove_title.setObjectName("remove_title")
        self.duration_input = QtWidgets.QLineEdit(Dialog)
        self.duration_input.setGeometry(QtCore.QRect(130, 230, 61, 21))
        self.duration_input.setObjectName("duration_input")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Adicionar/Remover Disco"))
        self.add_btn.setText(_translate("Dialog", "Adicionar"))
        self.remove_btn.setText(_translate("Dialog", "Remover"))
        self.artist.setText(_translate("Dialog", "Artista:"))
        self.add_record.setText(_translate("Dialog", "Disco:"))
        self.duration.setText(_translate("Dialog", "Duracao:"))
        self.tracks.setText(_translate("Dialog", "Nº de faixas:"))
        self.record_label.setText(_translate("Dialog", "Gravadora:"))
        self.grade.setText(_translate("Dialog", "Nota:"))
        self.goat_box.setText(
            _translate("Dialog", "Melhor Disco / Banda / Artista de todos os tempos.")
        )
        self.add_title.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p align="center"><span style=" font-size:18pt;">Preencha todos os campos </span></p><p align="center"><span style=" font-size:18pt;">abaixo para cadastrar um disco.</span></p></body></html>',
            )
        )
        self.remove_record.setText(_translate("Dialog", "Disco:"))
        self.remove_title.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p align="center"><span style=" font-size:18pt;">Qual disco deseja remover?</span></p></body></html>',
            )
        )
