# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addRemoveRecords.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 525)
        self.addBtn = QtWidgets.QPushButton(Dialog)
        self.addBtn.setGeometry(QtCore.QRect(50, 300, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.removeBtn = QtWidgets.QPushButton(Dialog)
        self.removeBtn.setGeometry(QtCore.QRect(50, 460, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.removeBtn.setFont(font)
        self.removeBtn.setObjectName("removeBtn")
        self.artist = QtWidgets.QLabel(Dialog)
        self.artist.setGeometry(QtCore.QRect(50, 150, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.artist.setFont(font)
        self.artist.setObjectName("artist")
        self.addRecord = QtWidgets.QLabel(Dialog)
        self.addRecord.setGeometry(QtCore.QRect(50, 110, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addRecord.setFont(font)
        self.addRecord.setObjectName("addRecord")
        self.duration = QtWidgets.QLabel(Dialog)
        self.duration.setGeometry(QtCore.QRect(50, 230, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.duration.setFont(font)
        self.duration.setObjectName("duration")
        self.tracks = QtWidgets.QLabel(Dialog)
        self.tracks.setGeometry(QtCore.QRect(200, 230, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tracks.setFont(font)
        self.tracks.setObjectName("tracks")
        self.recordLabel = QtWidgets.QLabel(Dialog)
        self.recordLabel.setGeometry(QtCore.QRect(50, 190, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recordLabel.setFont(font)
        self.recordLabel.setObjectName("recordLabel")
        self.grade = QtWidgets.QLabel(Dialog)
        self.grade.setGeometry(QtCore.QRect(380, 230, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.grade.setFont(font)
        self.grade.setObjectName("grade")
        self.goatBox = QtWidgets.QCheckBox(Dialog)
        self.goatBox.setGeometry(QtCore.QRect(50, 270, 451, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.goatBox.setFont(font)
        self.goatBox.setObjectName("goatBox")
        self.addTitle = QtWidgets.QLabel(Dialog)
        self.addTitle.setGeometry(QtCore.QRect(40, 10, 461, 81))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.addTitle.setFont(font)
        self.addTitle.setObjectName("addTitle")
        self.trackInput = QtWidgets.QLineEdit(Dialog)
        self.trackInput.setGeometry(QtCore.QRect(310, 230, 61, 21))
        self.trackInput.setObjectName("trackInput")
        self.scoreInput = QtWidgets.QLineEdit(Dialog)
        self.scoreInput.setGeometry(QtCore.QRect(430, 230, 61, 21))
        self.scoreInput.setObjectName("scoreInput")
        self.recordInput = QtWidgets.QLineEdit(Dialog)
        self.recordInput.setGeometry(QtCore.QRect(110, 110, 381, 21))
        self.recordInput.setObjectName("recordInput")
        self.artistInput = QtWidgets.QLineEdit(Dialog)
        self.artistInput.setGeometry(QtCore.QRect(120, 150, 371, 21))
        self.artistInput.setObjectName("artistInput")
        self.recordLabelInput = QtWidgets.QLineEdit(Dialog)
        self.recordLabelInput.setGeometry(QtCore.QRect(150, 190, 341, 21))
        self.recordLabelInput.setObjectName("recordLabelInput")
        self.removeRecord = QtWidgets.QLabel(Dialog)
        self.removeRecord.setGeometry(QtCore.QRect(50, 420, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.removeRecord.setFont(font)
        self.removeRecord.setObjectName("removeRecord")
        self.removeInput = QtWidgets.QLineEdit(Dialog)
        self.removeInput.setGeometry(QtCore.QRect(110, 420, 381, 21))
        self.removeInput.setObjectName("removeInput")
        self.removeTitle = QtWidgets.QLabel(Dialog)
        self.removeTitle.setGeometry(QtCore.QRect(100, 370, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.removeTitle.setFont(font)
        self.removeTitle.setObjectName("removeTitle")
        self.durationInput = QtWidgets.QLineEdit(Dialog)
        self.durationInput.setGeometry(QtCore.QRect(130, 230, 61, 21))
        self.durationInput.setObjectName("durationInput")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Adicionar/Remover Disco"))
        self.addBtn.setText(_translate("Dialog", "Adicionar"))
        self.removeBtn.setText(_translate("Dialog", "Remover"))
        self.artist.setText(_translate("Dialog", "Artista:"))
        self.addRecord.setText(_translate("Dialog", "Disco:"))
        self.duration.setText(_translate("Dialog", "Duracao:"))
        self.tracks.setText(_translate("Dialog", "Nº de faixas:"))
        self.recordLabel.setText(_translate("Dialog", "Gravadora:"))
        self.grade.setText(_translate("Dialog", "Nota:"))
        self.goatBox.setText(_translate("Dialog", "Melhor Disco / Banda / Artista de todos os tempos."))
        self.addTitle.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Preencha todos os campos </span></p><p align=\"center\"><span style=\" font-size:18pt;\">abaixo para cadastrar um disco.</span></p></body></html>"))
        self.removeRecord.setText(_translate("Dialog", "Disco:"))
        self.removeTitle.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Qual disco deseja remover?</span></p></body></html>"))
