# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchRecord.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(542, 525)
        self.searchBtn = QtWidgets.QPushButton(Dialog)
        self.searchBtn.setGeometry(QtCore.QRect(50, 130, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.searchBtn.setFont(font)
        self.searchBtn.setObjectName("searchBtn")
        self.removeRecord = QtWidgets.QLabel(Dialog)
        self.removeRecord.setGeometry(QtCore.QRect(50, 90, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.removeRecord.setFont(font)
        self.removeRecord.setObjectName("removeRecord")
        self.searchInput = QtWidgets.QLineEdit(Dialog)
        self.searchInput.setGeometry(QtCore.QRect(110, 90, 381, 21))
        self.searchInput.setObjectName("searchInput")
        self.mainTitle = QtWidgets.QLabel(Dialog)
        self.mainTitle.setGeometry(QtCore.QRect(100, 40, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mainTitle.setFont(font)
        self.mainTitle.setObjectName("mainTitle")
        self.recordLabel = QtWidgets.QLabel(Dialog)
        self.recordLabel.setGeometry(QtCore.QRect(50, 360, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recordLabel.setFont(font)
        self.recordLabel.setObjectName("recordLabel")
        self.goatBoxShow = QtWidgets.QCheckBox(Dialog)
        self.goatBoxShow.setGeometry(QtCore.QRect(50, 440, 451, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.goatBoxShow.setFont(font)
        self.goatBoxShow.setObjectName("goatBoxShow")
        self.artistShow = QtWidgets.QLineEdit(Dialog)
        self.artistShow.setGeometry(QtCore.QRect(120, 320, 371, 21))
        self.artistShow.setObjectName("artistShow")
        self.scoreShow = QtWidgets.QLineEdit(Dialog)
        self.scoreShow.setGeometry(QtCore.QRect(430, 400, 61, 21))
        self.scoreShow.setObjectName("scoreShow")
        self.durationShow = QtWidgets.QLineEdit(Dialog)
        self.durationShow.setGeometry(QtCore.QRect(130, 400, 61, 21))
        self.durationShow.setObjectName("durationShow")
        self.artist = QtWidgets.QLabel(Dialog)
        self.artist.setGeometry(QtCore.QRect(50, 320, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.artist.setFont(font)
        self.artist.setObjectName("artist")
        self.trackShow = QtWidgets.QLineEdit(Dialog)
        self.trackShow.setGeometry(QtCore.QRect(310, 400, 61, 21))
        self.trackShow.setObjectName("trackShow")
        self.recordShow = QtWidgets.QLineEdit(Dialog)
        self.recordShow.setGeometry(QtCore.QRect(110, 280, 381, 21))
        self.recordShow.setObjectName("recordShow")
        self.tracks = QtWidgets.QLabel(Dialog)
        self.tracks.setGeometry(QtCore.QRect(200, 400, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tracks.setFont(font)
        self.tracks.setObjectName("tracks")
        self.duration = QtWidgets.QLabel(Dialog)
        self.duration.setGeometry(QtCore.QRect(50, 400, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.duration.setFont(font)
        self.duration.setObjectName("duration")
        self.infoShow = QtWidgets.QLabel(Dialog)
        self.infoShow.setGeometry(QtCore.QRect(40, 210, 461, 81))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.infoShow.setFont(font)
        self.infoShow.setObjectName("infoShow")
        self.addRecord = QtWidgets.QLabel(Dialog)
        self.addRecord.setGeometry(QtCore.QRect(50, 280, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addRecord.setFont(font)
        self.addRecord.setObjectName("addRecord")
        self.grade = QtWidgets.QLabel(Dialog)
        self.grade.setGeometry(QtCore.QRect(380, 400, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.grade.setFont(font)
        self.grade.setObjectName("grade")
        self.recordLabelShow = QtWidgets.QLineEdit(Dialog)
        self.recordLabelShow.setGeometry(QtCore.QRect(150, 360, 341, 21))
        self.recordLabelShow.setObjectName("recordLabelShow")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Procurar Disco"))
        self.searchBtn.setText(_translate("Dialog", "Procurar"))
        self.removeRecord.setText(_translate("Dialog", "Disco:"))
        self.mainTitle.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Qual disco deseja encontrar?</span></p></body></html>"))
        self.recordLabel.setText(_translate("Dialog", "Gravadora:"))
        self.goatBoxShow.setText(_translate("Dialog", "Melhor Disco / Banda / Artista de todos os tempos."))
        self.artist.setText(_translate("Dialog", "Artista:"))
        self.tracks.setText(_translate("Dialog", "Nº de faixas:"))
        self.duration.setText(_translate("Dialog", "Duracao:"))
        self.infoShow.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Resultado da pesquisa:</p></body></html>"))
        self.addRecord.setText(_translate("Dialog", "Disco:"))
        self.grade.setText(_translate("Dialog", "Nota:"))
