# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchRecord.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(542, 525)
        self.search_btn = QtWidgets.QPushButton(Dialog)
        self.search_btn.setGeometry(QtCore.QRect(50, 130, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.remove_record = QtWidgets.QLabel(Dialog)
        self.remove_record.setGeometry(QtCore.QRect(50, 90, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.remove_record.setFont(font)
        self.remove_record.setObjectName("remove_record")
        self.search_input = QtWidgets.QLineEdit(Dialog)
        self.search_input.setGeometry(QtCore.QRect(110, 90, 381, 21))
        self.search_input.setObjectName("search_input")
        self.main_title = QtWidgets.QLabel(Dialog)
        self.main_title.setGeometry(QtCore.QRect(100, 40, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.main_title.setFont(font)
        self.main_title.setObjectName("main_title")
        self.record_label = QtWidgets.QLabel(Dialog)
        self.record_label.setGeometry(QtCore.QRect(50, 360, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.record_label.setFont(font)
        self.record_label.setObjectName("record_label")
        self.goat_box_show = QtWidgets.QCheckBox(Dialog)
        self.goat_box_show.setGeometry(QtCore.QRect(50, 440, 451, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.goat_box_show.setFont(font)
        self.goat_box_show.setObjectName("goat_box_show")
        self.artist_show = QtWidgets.QLineEdit(Dialog)
        self.artist_show.setGeometry(QtCore.QRect(120, 320, 371, 21))
        self.artist_show.setObjectName("artist_show")
        self.score_show = QtWidgets.QLineEdit(Dialog)
        self.score_show.setGeometry(QtCore.QRect(430, 400, 61, 21))
        self.score_show.setObjectName("score_show")
        self.duration_show = QtWidgets.QLineEdit(Dialog)
        self.duration_show.setGeometry(QtCore.QRect(130, 400, 61, 21))
        self.duration_show.setObjectName("duration_show")
        self.artist = QtWidgets.QLabel(Dialog)
        self.artist.setGeometry(QtCore.QRect(50, 320, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.artist.setFont(font)
        self.artist.setObjectName("artist")
        self.track_show = QtWidgets.QLineEdit(Dialog)
        self.track_show.setGeometry(QtCore.QRect(310, 400, 61, 21))
        self.track_show.setObjectName("track_show")
        self.record_show = QtWidgets.QLineEdit(Dialog)
        self.record_show.setGeometry(QtCore.QRect(110, 280, 381, 21))
        self.record_show.setObjectName("record_show")
        self.tracks = QtWidgets.QLabel(Dialog)
        self.tracks.setGeometry(QtCore.QRect(200, 400, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tracks.setFont(font)
        self.tracks.setObjectName("tracks")
        self.duration = QtWidgets.QLabel(Dialog)
        self.duration.setGeometry(QtCore.QRect(50, 400, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.duration.setFont(font)
        self.duration.setObjectName("duration")
        self.info_show = QtWidgets.QLabel(Dialog)
        self.info_show.setGeometry(QtCore.QRect(40, 210, 461, 81))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.info_show.setFont(font)
        self.info_show.setObjectName("info_show")
        self.add_record = QtWidgets.QLabel(Dialog)
        self.add_record.setGeometry(QtCore.QRect(50, 280, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_record.setFont(font)
        self.add_record.setObjectName("add_record")
        self.grade = QtWidgets.QLabel(Dialog)
        self.grade.setGeometry(QtCore.QRect(380, 400, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.grade.setFont(font)
        self.grade.setObjectName("grade")
        self.record_label_show = QtWidgets.QLineEdit(Dialog)
        self.record_label_show.setGeometry(QtCore.QRect(150, 360, 341, 21))
        self.record_label_show.setObjectName("record_label_show")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Procurar Disco"))
        self.search_btn.setText(_translate("Dialog", "Procurar"))
        self.remove_record.setText(_translate("Dialog", "Disco:"))
        self.main_title.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p align="center"><span style=" font-size:18pt;">Qual disco deseja encontrar?</span></p></body></html>',
            )
        )
        self.record_label.setText(_translate("Dialog", "Gravadora:"))
        self.goat_box_show.setText(
            _translate("Dialog", "Melhor Disco / Banda / Artista de todos os tempos.")
        )
        self.artist.setText(_translate("Dialog", "Artista:"))
        self.tracks.setText(_translate("Dialog", "Nº de faixas:"))
        self.duration.setText(_translate("Dialog", "Duracao:"))
        self.info_show.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p align="center">Resultado da pesquisa:</p></body></html>',
            )
        )
        self.add_record.setText(_translate("Dialog", "Disco:"))
        self.grade.setText(_translate("Dialog", "Nota:"))
